### Example request against external test server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create a new Todo
POST http://localhost:8081/api/v1/todos
Content-Type: application/json

{
  "title": "Write POST endpoint",
  "status": "PENDING"
}

### Update an existing Todo by ID
PUT http://localhost:8081/api/v1/todos/cd42c555-7bba-44bb-bc51-6d0f66cbbdd6
Content-Type: application/json

{
  "title": "Ship CRUD today",
  "status": "DONE"
}

### Delete a Todo by ID
DELETE http://localhost:8081/api/v1/todos/2f4640bb-ba76-409d-877a-0637f591be39

### Get a single Todo by ID
GET http://localhost:8081/api/v1/todos/2f4640bb-ba76-409d-877a-0637f591be39

###
GET http://localhost:8081/api/v1/todos?priority=HIGH

###
GET http://localhost:8081/api/v1/todos?status=PENDING&dueBefore=2025-10-05

###
GET http://localhost:8081/api/v1/todos?dueAfter=2025-09-25&dueBefore=2025-10-09

###
GET http://localhost:8081/api/v1/todos?q=career

###
POST http://localhost:8081/api/v1/todos
Content-Type: application/json

{
"title": "Test Postgres persistence #2", "dueDate": "2025-10-15"
}

###
POST http://localhost:8081/api/v1/todos
Content-Type: application/json

{
  "title": " "
}

###
POST http://localhost:8081/api/v1/todos
Content-Type: application/json

{
  "title": "Backdated", "dueDate": "2024-01-01"
}