### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8081/api/v1/todos
Content-Type: application/json

{
  "title": "Write POST endpoint",
  "status": "PENDING"
}

###
PUT http://localhost:8081/api/v1/todos/cd42c555-7bba-44bb-bc51-6d0f66cbbdd6
Content-Type: application/json

{ "title": "Ship CRUD today", "status": "DONE" }

###
DELETE http://localhost:8081/api/v1/todos/2f4640bb-ba76-409d-877a-0637f591be39

###
GET http://localhost:8081/api/v1/todos/2f4640bb-ba76-409d-877a-0637f591be39
